name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'

      - name: Download dependencies
        run: go mod download

      - name: Build
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0
        run: |
          go build -o soletrabot ./soletrabot

      - name: Copy binary to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ vars.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "soletrabot"
          target: "/home/ubuntu/soletrabot/"

      - name: Restart service
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ vars.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            sudo systemctl restart soletrabot
            sudo systemctl status soletrabot --no-pager
